### ISSUE TITLE
Update ingress configuration

### ISSUE THREAD

**Issue by Nehoko** [lukaszbudnik/keycloak-kubernetes#20]
Hi! I suggest you to update a bit your ingress configuration for keycloak:
```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - fake
      secretName: auth-tls-secret
  rules:
  - host: "auth.localtest.me"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: keycloak
            port:
              number: 443
```

What's the difference?
- proxy-buffer-size added to prevent 502 error
- ingress class name is not annotation anymore. They moved it into `spec.ingressClassName`.
